modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/gelonsoft/silent-addons/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silent-addons"
logoFile="logo.png"
credits="Thanks for this mod goes to SilentChaos512"
authors="gelonsoft"

[[mods]]
    modId="silentaddons"
    version="${file.jarVersion}"
    displayName="Silent Addons"
    updateJSONURL="https://raw.githubusercontent.com/gelonsoft/silent-addons/master/update.json"
    description='''
    Modular and upgradeable tools. Allows full customization of parts used in gear crafting, even user-defined parts!
    '''

[[dependencies.silentaddons]]
    modId="forge"
    mandatory=true
    versionRange="[28.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentaddons]]
    modId="silentgear"
    mandatory=true
    versionRange="[1.4.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentaddons]]
    modId="silentlib"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"
